# ===============================
# Spring Boot App
# ===============================
spring.application.name=backend
server.port=8080

# ===============================
# MongoDB Config
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/news_db
spring.data.mongodb.database=news_db
spring.data.mongodb.auto-index-creation=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# ===============================
# NewsAPI Config
# ===============================
newsapi.key=1785302b739843b28c2a0f84e472cead
newsapi.baseurl=https://newsapi.org/v2

# ===============================
# ML FastAPI Service (running on port 5001)
# ===============================
ml.api.baseurl=http://127.0.0.1:5001
